### ISSUE TITLE
ProtMap getting stuck

### ISSUE THREAD

**Issue by rohitmpibpc** [CWRU-CPB/ProtMapMS#4]
Hi Sean,

I tried to run ProtMap on 4 LC-MS runs. The analysis was for trypsin digestion and complex of 2 proteins. The program ran fine when i used 0 ms and 10 ms/0 ms and 20 ms/0 ms and 30 ms. It yielded close to 35 peptides.
But the program got stuck for hours when i attempted to run all exposures together. 
Could you help with this issue ?

Thanks,
Rohit

**Comment by many-states** [comment]
It sounds like it might be running out of memory. Try changing the launch command to:

java -Xmx2g -Xms2g -jar ProtMapMS.jar --gui

So that the JVM initializes with a 2GB heap.

**Comment by rohitmpibpc** [comment]
Hi Sean,

I tried changing the run.bat file with above command. I was not able to open it. 
Could you please help ?
I could not attached original run.bat file here.
It will be great if you could modify it. I will try to run sample here.


Rohit
