### ISSUE TITLE
ProtMap not running few files

### ISSUE THREAD

**Issue by rohitmpibpc** [CWRU-CPB/ProtMapMS#5]
Hi Sean,

I am not able to properly run 2 sample files out of 3.

0 ms - Program gives error.
10 ms - Program runs and I see peak areas.
15 ms - Program runs but i don't get any peptide.

I also attempted to run these files together like 10 ms/15 ms.
In this case, program gets stuck.

If I run these files with 0 ms then program gives error.

I have tried using other software and all these time points give many peptides and modifications.

Could you please help ?

Rohit

**Comment by many-states** [comment]
Committed a new version that fixes an index out of bounds error when MS2 scan is empty. I believe this fixes the issue.
