### ISSUE TITLE
Adding new modifications - ProtMap does not run

### ISSUE THREAD

**Issue by rohitmpibpc** [CWRU-CPB/ProtMapMS#6]
Hi Sean,

I have tried to add new modifications in the file which we started with.
In this case, I am unable to run and program get's stuck. I am unsure its memory issue
or mistake in adding modifications.

Let me know how can we sort out this problem. I have emailed you file with added modifications.

Rohit

**Comment by many-states** [comment]
I believe it is a memory issue. Increase the amount of memory allocated to the JVM.
